param(
    [switch]$Remote,
    [string]$CondaEnvironmentName = "standard_ml_codex_env",
    [string]$PythonExecutable = "python",
    [string]$RemoteHostAlias = "xilab-remote",
    [string]$RemoteRepositoryPath = $(if ($env:STANDARDML_REMOTE_TRAINING_REPO_PATH) { $env:STANDARDML_REMOTE_TRAINING_REPO_PATH } else { "C:\Users\Martina Salami\Documents\Davide\Physics-Informed-Neural-Networks" }),
    [string]$RemoteCondaEnvironmentName = $(if ($env:STANDARDML_REMOTE_TRAINING_CONDA_ENV) { $env:STANDARDML_REMOTE_TRAINING_CONDA_ENV } else { "standard_ml_lan_node" })
)

$ErrorActionPreference = "Stop"
$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = (Resolve-Path (Join-Path $scriptDirectory "..\.." )).Path
Set-Location $projectRoot
. (Join-Path $scriptDirectory "invoke_exact_paper_campaign_local.ps1")

$campaignConfigRoot = "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign"
$planningReportPath = "doc\reports\campaign_plans\track1\exact_paper\2026-04-19-01-04-28_track1_remaining_family_residual_cellwise_closure_campaigns_plan_report.md"
$campaignName = "track1_hgbm_residual_cellwise_closure_campaign_2026_04_19_01_04_28"
$campaignConfigFileNameList = @(
    "001_track1_hgbm_amplitude_0_closure_attempt_01.yaml"
    "002_track1_hgbm_amplitude_0_closure_attempt_02.yaml"
    "003_track1_hgbm_amplitude_0_closure_attempt_03.yaml"
    "004_track1_hgbm_amplitude_0_closure_attempt_04.yaml"
    "005_track1_hgbm_amplitude_0_closure_attempt_05.yaml"
    "006_track1_hgbm_amplitude_0_closure_attempt_06.yaml"
    "007_track1_hgbm_amplitude_1_closure_attempt_01.yaml"
    "008_track1_hgbm_amplitude_1_closure_attempt_02.yaml"
    "009_track1_hgbm_amplitude_1_closure_attempt_03.yaml"
    "010_track1_hgbm_amplitude_1_closure_attempt_04.yaml"
    "011_track1_hgbm_amplitude_1_closure_attempt_05.yaml"
    "012_track1_hgbm_amplitude_1_closure_attempt_06.yaml"
    "013_track1_hgbm_amplitude_3_closure_attempt_01.yaml"
    "014_track1_hgbm_amplitude_3_closure_attempt_02.yaml"
    "015_track1_hgbm_amplitude_3_closure_attempt_03.yaml"
    "016_track1_hgbm_amplitude_3_closure_attempt_04.yaml"
    "017_track1_hgbm_amplitude_3_closure_attempt_05.yaml"
    "018_track1_hgbm_amplitude_3_closure_attempt_06.yaml"
    "019_track1_hgbm_amplitude_39_closure_attempt_01.yaml"
    "020_track1_hgbm_amplitude_39_closure_attempt_02.yaml"
    "021_track1_hgbm_amplitude_39_closure_attempt_03.yaml"
    "022_track1_hgbm_amplitude_39_closure_attempt_04.yaml"
    "023_track1_hgbm_amplitude_39_closure_attempt_05.yaml"
    "024_track1_hgbm_amplitude_39_closure_attempt_06.yaml"
    "025_track1_hgbm_amplitude_40_closure_attempt_01.yaml"
    "026_track1_hgbm_amplitude_40_closure_attempt_02.yaml"
    "027_track1_hgbm_amplitude_40_closure_attempt_03.yaml"
    "028_track1_hgbm_amplitude_40_closure_attempt_04.yaml"
    "029_track1_hgbm_amplitude_40_closure_attempt_05.yaml"
    "030_track1_hgbm_amplitude_40_closure_attempt_06.yaml"
    "031_track1_hgbm_amplitude_78_closure_attempt_01.yaml"
    "032_track1_hgbm_amplitude_78_closure_attempt_02.yaml"
    "033_track1_hgbm_amplitude_78_closure_attempt_03.yaml"
    "034_track1_hgbm_amplitude_78_closure_attempt_04.yaml"
    "035_track1_hgbm_amplitude_78_closure_attempt_05.yaml"
    "036_track1_hgbm_amplitude_78_closure_attempt_06.yaml"
    "037_track1_hgbm_amplitude_81_closure_attempt_01.yaml"
    "038_track1_hgbm_amplitude_81_closure_attempt_02.yaml"
    "039_track1_hgbm_amplitude_81_closure_attempt_03.yaml"
    "040_track1_hgbm_amplitude_81_closure_attempt_04.yaml"
    "041_track1_hgbm_amplitude_81_closure_attempt_05.yaml"
    "042_track1_hgbm_amplitude_81_closure_attempt_06.yaml"
    "043_track1_hgbm_amplitude_156_closure_attempt_01.yaml"
    "044_track1_hgbm_amplitude_156_closure_attempt_02.yaml"
    "045_track1_hgbm_amplitude_156_closure_attempt_03.yaml"
    "046_track1_hgbm_amplitude_156_closure_attempt_04.yaml"
    "047_track1_hgbm_amplitude_156_closure_attempt_05.yaml"
    "048_track1_hgbm_amplitude_156_closure_attempt_06.yaml"
    "049_track1_hgbm_amplitude_162_closure_attempt_01.yaml"
    "050_track1_hgbm_amplitude_162_closure_attempt_02.yaml"
    "051_track1_hgbm_amplitude_162_closure_attempt_03.yaml"
    "052_track1_hgbm_amplitude_162_closure_attempt_04.yaml"
    "053_track1_hgbm_amplitude_162_closure_attempt_05.yaml"
    "054_track1_hgbm_amplitude_162_closure_attempt_06.yaml"
    "055_track1_hgbm_amplitude_240_closure_attempt_01.yaml"
    "056_track1_hgbm_amplitude_240_closure_attempt_02.yaml"
    "057_track1_hgbm_amplitude_240_closure_attempt_03.yaml"
    "058_track1_hgbm_amplitude_240_closure_attempt_04.yaml"
    "059_track1_hgbm_amplitude_240_closure_attempt_05.yaml"
    "060_track1_hgbm_amplitude_240_closure_attempt_06.yaml"
    "061_track1_hgbm_phase_1_closure_attempt_01.yaml"
    "062_track1_hgbm_phase_1_closure_attempt_02.yaml"
    "063_track1_hgbm_phase_1_closure_attempt_03.yaml"
    "064_track1_hgbm_phase_1_closure_attempt_04.yaml"
    "065_track1_hgbm_phase_1_closure_attempt_05.yaml"
    "066_track1_hgbm_phase_1_closure_attempt_06.yaml"
    "067_track1_hgbm_phase_3_closure_attempt_01.yaml"
    "068_track1_hgbm_phase_3_closure_attempt_02.yaml"
    "069_track1_hgbm_phase_3_closure_attempt_03.yaml"
    "070_track1_hgbm_phase_3_closure_attempt_04.yaml"
    "071_track1_hgbm_phase_3_closure_attempt_05.yaml"
    "072_track1_hgbm_phase_3_closure_attempt_06.yaml"
    "073_track1_hgbm_phase_39_closure_attempt_01.yaml"
    "074_track1_hgbm_phase_39_closure_attempt_02.yaml"
    "075_track1_hgbm_phase_39_closure_attempt_03.yaml"
    "076_track1_hgbm_phase_39_closure_attempt_04.yaml"
    "077_track1_hgbm_phase_39_closure_attempt_05.yaml"
    "078_track1_hgbm_phase_39_closure_attempt_06.yaml"
    "079_track1_hgbm_phase_40_closure_attempt_01.yaml"
    "080_track1_hgbm_phase_40_closure_attempt_02.yaml"
    "081_track1_hgbm_phase_40_closure_attempt_03.yaml"
    "082_track1_hgbm_phase_40_closure_attempt_04.yaml"
    "083_track1_hgbm_phase_40_closure_attempt_05.yaml"
    "084_track1_hgbm_phase_40_closure_attempt_06.yaml"
    "085_track1_hgbm_phase_78_closure_attempt_01.yaml"
    "086_track1_hgbm_phase_78_closure_attempt_02.yaml"
    "087_track1_hgbm_phase_78_closure_attempt_03.yaml"
    "088_track1_hgbm_phase_78_closure_attempt_04.yaml"
    "089_track1_hgbm_phase_78_closure_attempt_05.yaml"
    "090_track1_hgbm_phase_78_closure_attempt_06.yaml"
    "091_track1_hgbm_phase_81_closure_attempt_01.yaml"
    "092_track1_hgbm_phase_81_closure_attempt_02.yaml"
    "093_track1_hgbm_phase_81_closure_attempt_03.yaml"
    "094_track1_hgbm_phase_81_closure_attempt_04.yaml"
    "095_track1_hgbm_phase_81_closure_attempt_05.yaml"
    "096_track1_hgbm_phase_81_closure_attempt_06.yaml"
    "097_track1_hgbm_phase_156_closure_attempt_01.yaml"
    "098_track1_hgbm_phase_156_closure_attempt_02.yaml"
    "099_track1_hgbm_phase_156_closure_attempt_03.yaml"
    "100_track1_hgbm_phase_156_closure_attempt_04.yaml"
    "101_track1_hgbm_phase_156_closure_attempt_05.yaml"
    "102_track1_hgbm_phase_156_closure_attempt_06.yaml"
    "103_track1_hgbm_phase_162_closure_attempt_01.yaml"
    "104_track1_hgbm_phase_162_closure_attempt_02.yaml"
    "105_track1_hgbm_phase_162_closure_attempt_03.yaml"
    "106_track1_hgbm_phase_162_closure_attempt_04.yaml"
    "107_track1_hgbm_phase_162_closure_attempt_05.yaml"
    "108_track1_hgbm_phase_162_closure_attempt_06.yaml"
    "109_track1_hgbm_phase_240_closure_attempt_01.yaml"
    "110_track1_hgbm_phase_240_closure_attempt_02.yaml"
    "111_track1_hgbm_phase_240_closure_attempt_03.yaml"
    "112_track1_hgbm_phase_240_closure_attempt_04.yaml"
    "113_track1_hgbm_phase_240_closure_attempt_05.yaml"
    "114_track1_hgbm_phase_240_closure_attempt_06.yaml"
)
$campaignConfigPathList = @(
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\001_track1_hgbm_amplitude_0_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\002_track1_hgbm_amplitude_0_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\003_track1_hgbm_amplitude_0_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\004_track1_hgbm_amplitude_0_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\005_track1_hgbm_amplitude_0_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\006_track1_hgbm_amplitude_0_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\007_track1_hgbm_amplitude_1_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\008_track1_hgbm_amplitude_1_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\009_track1_hgbm_amplitude_1_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\010_track1_hgbm_amplitude_1_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\011_track1_hgbm_amplitude_1_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\012_track1_hgbm_amplitude_1_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\013_track1_hgbm_amplitude_3_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\014_track1_hgbm_amplitude_3_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\015_track1_hgbm_amplitude_3_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\016_track1_hgbm_amplitude_3_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\017_track1_hgbm_amplitude_3_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\018_track1_hgbm_amplitude_3_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\019_track1_hgbm_amplitude_39_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\020_track1_hgbm_amplitude_39_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\021_track1_hgbm_amplitude_39_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\022_track1_hgbm_amplitude_39_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\023_track1_hgbm_amplitude_39_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\024_track1_hgbm_amplitude_39_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\025_track1_hgbm_amplitude_40_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\026_track1_hgbm_amplitude_40_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\027_track1_hgbm_amplitude_40_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\028_track1_hgbm_amplitude_40_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\029_track1_hgbm_amplitude_40_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\030_track1_hgbm_amplitude_40_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\031_track1_hgbm_amplitude_78_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\032_track1_hgbm_amplitude_78_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\033_track1_hgbm_amplitude_78_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\034_track1_hgbm_amplitude_78_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\035_track1_hgbm_amplitude_78_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\036_track1_hgbm_amplitude_78_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\037_track1_hgbm_amplitude_81_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\038_track1_hgbm_amplitude_81_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\039_track1_hgbm_amplitude_81_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\040_track1_hgbm_amplitude_81_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\041_track1_hgbm_amplitude_81_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\042_track1_hgbm_amplitude_81_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\043_track1_hgbm_amplitude_156_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\044_track1_hgbm_amplitude_156_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\045_track1_hgbm_amplitude_156_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\046_track1_hgbm_amplitude_156_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\047_track1_hgbm_amplitude_156_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\048_track1_hgbm_amplitude_156_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\049_track1_hgbm_amplitude_162_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\050_track1_hgbm_amplitude_162_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\051_track1_hgbm_amplitude_162_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\052_track1_hgbm_amplitude_162_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\053_track1_hgbm_amplitude_162_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\054_track1_hgbm_amplitude_162_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\055_track1_hgbm_amplitude_240_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\056_track1_hgbm_amplitude_240_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\057_track1_hgbm_amplitude_240_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\058_track1_hgbm_amplitude_240_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\059_track1_hgbm_amplitude_240_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\060_track1_hgbm_amplitude_240_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\061_track1_hgbm_phase_1_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\062_track1_hgbm_phase_1_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\063_track1_hgbm_phase_1_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\064_track1_hgbm_phase_1_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\065_track1_hgbm_phase_1_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\066_track1_hgbm_phase_1_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\067_track1_hgbm_phase_3_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\068_track1_hgbm_phase_3_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\069_track1_hgbm_phase_3_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\070_track1_hgbm_phase_3_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\071_track1_hgbm_phase_3_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\072_track1_hgbm_phase_3_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\073_track1_hgbm_phase_39_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\074_track1_hgbm_phase_39_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\075_track1_hgbm_phase_39_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\076_track1_hgbm_phase_39_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\077_track1_hgbm_phase_39_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\078_track1_hgbm_phase_39_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\079_track1_hgbm_phase_40_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\080_track1_hgbm_phase_40_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\081_track1_hgbm_phase_40_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\082_track1_hgbm_phase_40_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\083_track1_hgbm_phase_40_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\084_track1_hgbm_phase_40_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\085_track1_hgbm_phase_78_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\086_track1_hgbm_phase_78_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\087_track1_hgbm_phase_78_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\088_track1_hgbm_phase_78_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\089_track1_hgbm_phase_78_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\090_track1_hgbm_phase_78_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\091_track1_hgbm_phase_81_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\092_track1_hgbm_phase_81_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\093_track1_hgbm_phase_81_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\094_track1_hgbm_phase_81_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\095_track1_hgbm_phase_81_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\096_track1_hgbm_phase_81_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\097_track1_hgbm_phase_156_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\098_track1_hgbm_phase_156_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\099_track1_hgbm_phase_156_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\100_track1_hgbm_phase_156_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\101_track1_hgbm_phase_156_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\102_track1_hgbm_phase_156_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\103_track1_hgbm_phase_162_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\104_track1_hgbm_phase_162_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\105_track1_hgbm_phase_162_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\106_track1_hgbm_phase_162_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\107_track1_hgbm_phase_162_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\108_track1_hgbm_phase_162_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\109_track1_hgbm_phase_240_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\110_track1_hgbm_phase_240_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\111_track1_hgbm_phase_240_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\112_track1_hgbm_phase_240_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\113_track1_hgbm_phase_240_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-19_track1_hgbm_residual_cellwise_closure_campaign\114_track1_hgbm_phase_240_closure_attempt_06.yaml"
)
$runNameList = @(
    "track1_hgbm_amplitude_0_closure_attempt_01"
    "track1_hgbm_amplitude_0_closure_attempt_02"
    "track1_hgbm_amplitude_0_closure_attempt_03"
    "track1_hgbm_amplitude_0_closure_attempt_04"
    "track1_hgbm_amplitude_0_closure_attempt_05"
    "track1_hgbm_amplitude_0_closure_attempt_06"
    "track1_hgbm_amplitude_1_closure_attempt_01"
    "track1_hgbm_amplitude_1_closure_attempt_02"
    "track1_hgbm_amplitude_1_closure_attempt_03"
    "track1_hgbm_amplitude_1_closure_attempt_04"
    "track1_hgbm_amplitude_1_closure_attempt_05"
    "track1_hgbm_amplitude_1_closure_attempt_06"
    "track1_hgbm_amplitude_3_closure_attempt_01"
    "track1_hgbm_amplitude_3_closure_attempt_02"
    "track1_hgbm_amplitude_3_closure_attempt_03"
    "track1_hgbm_amplitude_3_closure_attempt_04"
    "track1_hgbm_amplitude_3_closure_attempt_05"
    "track1_hgbm_amplitude_3_closure_attempt_06"
    "track1_hgbm_amplitude_39_closure_attempt_01"
    "track1_hgbm_amplitude_39_closure_attempt_02"
    "track1_hgbm_amplitude_39_closure_attempt_03"
    "track1_hgbm_amplitude_39_closure_attempt_04"
    "track1_hgbm_amplitude_39_closure_attempt_05"
    "track1_hgbm_amplitude_39_closure_attempt_06"
    "track1_hgbm_amplitude_40_closure_attempt_01"
    "track1_hgbm_amplitude_40_closure_attempt_02"
    "track1_hgbm_amplitude_40_closure_attempt_03"
    "track1_hgbm_amplitude_40_closure_attempt_04"
    "track1_hgbm_amplitude_40_closure_attempt_05"
    "track1_hgbm_amplitude_40_closure_attempt_06"
    "track1_hgbm_amplitude_78_closure_attempt_01"
    "track1_hgbm_amplitude_78_closure_attempt_02"
    "track1_hgbm_amplitude_78_closure_attempt_03"
    "track1_hgbm_amplitude_78_closure_attempt_04"
    "track1_hgbm_amplitude_78_closure_attempt_05"
    "track1_hgbm_amplitude_78_closure_attempt_06"
    "track1_hgbm_amplitude_81_closure_attempt_01"
    "track1_hgbm_amplitude_81_closure_attempt_02"
    "track1_hgbm_amplitude_81_closure_attempt_03"
    "track1_hgbm_amplitude_81_closure_attempt_04"
    "track1_hgbm_amplitude_81_closure_attempt_05"
    "track1_hgbm_amplitude_81_closure_attempt_06"
    "track1_hgbm_amplitude_156_closure_attempt_01"
    "track1_hgbm_amplitude_156_closure_attempt_02"
    "track1_hgbm_amplitude_156_closure_attempt_03"
    "track1_hgbm_amplitude_156_closure_attempt_04"
    "track1_hgbm_amplitude_156_closure_attempt_05"
    "track1_hgbm_amplitude_156_closure_attempt_06"
    "track1_hgbm_amplitude_162_closure_attempt_01"
    "track1_hgbm_amplitude_162_closure_attempt_02"
    "track1_hgbm_amplitude_162_closure_attempt_03"
    "track1_hgbm_amplitude_162_closure_attempt_04"
    "track1_hgbm_amplitude_162_closure_attempt_05"
    "track1_hgbm_amplitude_162_closure_attempt_06"
    "track1_hgbm_amplitude_240_closure_attempt_01"
    "track1_hgbm_amplitude_240_closure_attempt_02"
    "track1_hgbm_amplitude_240_closure_attempt_03"
    "track1_hgbm_amplitude_240_closure_attempt_04"
    "track1_hgbm_amplitude_240_closure_attempt_05"
    "track1_hgbm_amplitude_240_closure_attempt_06"
    "track1_hgbm_phase_1_closure_attempt_01"
    "track1_hgbm_phase_1_closure_attempt_02"
    "track1_hgbm_phase_1_closure_attempt_03"
    "track1_hgbm_phase_1_closure_attempt_04"
    "track1_hgbm_phase_1_closure_attempt_05"
    "track1_hgbm_phase_1_closure_attempt_06"
    "track1_hgbm_phase_3_closure_attempt_01"
    "track1_hgbm_phase_3_closure_attempt_02"
    "track1_hgbm_phase_3_closure_attempt_03"
    "track1_hgbm_phase_3_closure_attempt_04"
    "track1_hgbm_phase_3_closure_attempt_05"
    "track1_hgbm_phase_3_closure_attempt_06"
    "track1_hgbm_phase_39_closure_attempt_01"
    "track1_hgbm_phase_39_closure_attempt_02"
    "track1_hgbm_phase_39_closure_attempt_03"
    "track1_hgbm_phase_39_closure_attempt_04"
    "track1_hgbm_phase_39_closure_attempt_05"
    "track1_hgbm_phase_39_closure_attempt_06"
    "track1_hgbm_phase_40_closure_attempt_01"
    "track1_hgbm_phase_40_closure_attempt_02"
    "track1_hgbm_phase_40_closure_attempt_03"
    "track1_hgbm_phase_40_closure_attempt_04"
    "track1_hgbm_phase_40_closure_attempt_05"
    "track1_hgbm_phase_40_closure_attempt_06"
    "track1_hgbm_phase_78_closure_attempt_01"
    "track1_hgbm_phase_78_closure_attempt_02"
    "track1_hgbm_phase_78_closure_attempt_03"
    "track1_hgbm_phase_78_closure_attempt_04"
    "track1_hgbm_phase_78_closure_attempt_05"
    "track1_hgbm_phase_78_closure_attempt_06"
    "track1_hgbm_phase_81_closure_attempt_01"
    "track1_hgbm_phase_81_closure_attempt_02"
    "track1_hgbm_phase_81_closure_attempt_03"
    "track1_hgbm_phase_81_closure_attempt_04"
    "track1_hgbm_phase_81_closure_attempt_05"
    "track1_hgbm_phase_81_closure_attempt_06"
    "track1_hgbm_phase_156_closure_attempt_01"
    "track1_hgbm_phase_156_closure_attempt_02"
    "track1_hgbm_phase_156_closure_attempt_03"
    "track1_hgbm_phase_156_closure_attempt_04"
    "track1_hgbm_phase_156_closure_attempt_05"
    "track1_hgbm_phase_156_closure_attempt_06"
    "track1_hgbm_phase_162_closure_attempt_01"
    "track1_hgbm_phase_162_closure_attempt_02"
    "track1_hgbm_phase_162_closure_attempt_03"
    "track1_hgbm_phase_162_closure_attempt_04"
    "track1_hgbm_phase_162_closure_attempt_05"
    "track1_hgbm_phase_162_closure_attempt_06"
    "track1_hgbm_phase_240_closure_attempt_01"
    "track1_hgbm_phase_240_closure_attempt_02"
    "track1_hgbm_phase_240_closure_attempt_03"
    "track1_hgbm_phase_240_closure_attempt_04"
    "track1_hgbm_phase_240_closure_attempt_05"
    "track1_hgbm_phase_240_closure_attempt_06"
)

if ($Remote) {
    & ".\scripts\campaigns\track1\exact_paper\run_exact_paper_campaign_remote.ps1" `
        -CampaignName $campaignName `
        -PlanningReportPath $planningReportPath `
        -LauncherRelativePath "scripts\campaigns\track1\exact_paper\run_track1_hgbm_residual_cellwise_closure_campaign.ps1" `
        -CampaignConfigPathList $campaignConfigPathList `
        -RunNameList $runNameList `
        -RemoteHostAlias $RemoteHostAlias `
        -RemoteRepositoryPath $RemoteRepositoryPath `
        -RemoteCondaEnvironmentName $RemoteCondaEnvironmentName
    exit $LASTEXITCODE
}

$nativeExitCode = Invoke-ExactPaperCampaignLocal `
    -CampaignName $campaignName `
    -PlanningReportPath $planningReportPath `
    -CampaignConfigRoot $campaignConfigRoot `
    -CampaignConfigFileNameList $campaignConfigFileNameList `
    -CondaEnvironmentName $CondaEnvironmentName `
    -PythonExecutable $PythonExecutable
exit $nativeExitCode
