param(
    [switch]$Remote,
    [string]$CondaEnvironmentName = "standard_ml_codex_env",
    [string]$PythonExecutable = "python",
    [string]$RemoteHostAlias = "xilab-remote",
    [string]$RemoteRepositoryPath = $(if ($env:STANDARDML_REMOTE_TRAINING_REPO_PATH) { $env:STANDARDML_REMOTE_TRAINING_REPO_PATH } else { "C:\Users\Martina Salami\Documents\Davide\Physics-Informed-Neural-Networks" }),
    [string]$RemoteCondaEnvironmentName = $(if ($env:STANDARDML_REMOTE_TRAINING_CONDA_ENV) { $env:STANDARDML_REMOTE_TRAINING_CONDA_ENV } else { "standard_ml_lan_node" })
)

$ErrorActionPreference = "Stop"
$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = (Resolve-Path (Join-Path $scriptDirectory "..\..\..\.." )).Path
Set-Location $projectRoot
. (Join-Path $scriptDirectory "invoke_exact_paper_campaign_local.ps1")

$campaignConfigRoot = "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign"
$planningReportPath = "doc\reports\campaign_plans\track1\exact_paper\2026-04-20-23-50-13_track1_open_cell_full_matrix_closure_campaigns_plan_report.md"
$campaignName = "track1_hgbm_open_cell_full_matrix_closure_campaign_2026_04_20_23_50_13"
$campaignConfigFileNameList = @(
    "001_track1_hgbm_amplitude_39_closure_attempt_01.yaml"
    "002_track1_hgbm_amplitude_39_closure_attempt_02.yaml"
    "003_track1_hgbm_amplitude_39_closure_attempt_03.yaml"
    "004_track1_hgbm_amplitude_39_closure_attempt_04.yaml"
    "005_track1_hgbm_amplitude_39_closure_attempt_05.yaml"
    "006_track1_hgbm_amplitude_39_closure_attempt_06.yaml"
    "007_track1_hgbm_amplitude_39_closure_attempt_07.yaml"
    "008_track1_hgbm_amplitude_39_closure_attempt_08.yaml"
    "009_track1_hgbm_amplitude_39_closure_attempt_09.yaml"
    "010_track1_hgbm_amplitude_39_closure_attempt_10.yaml"
    "011_track1_hgbm_amplitude_39_closure_attempt_11.yaml"
    "012_track1_hgbm_amplitude_39_closure_attempt_12.yaml"
    "013_track1_hgbm_amplitude_39_closure_attempt_13.yaml"
    "014_track1_hgbm_amplitude_39_closure_attempt_14.yaml"
    "015_track1_hgbm_amplitude_39_closure_attempt_15.yaml"
    "016_track1_hgbm_amplitude_39_closure_attempt_16.yaml"
    "017_track1_hgbm_amplitude_39_closure_attempt_17.yaml"
    "018_track1_hgbm_amplitude_39_closure_attempt_18.yaml"
    "019_track1_hgbm_amplitude_39_closure_attempt_19.yaml"
    "020_track1_hgbm_amplitude_39_closure_attempt_20.yaml"
    "021_track1_hgbm_amplitude_39_closure_attempt_21.yaml"
    "022_track1_hgbm_amplitude_39_closure_attempt_22.yaml"
    "023_track1_hgbm_amplitude_39_closure_attempt_23.yaml"
    "024_track1_hgbm_amplitude_39_closure_attempt_24.yaml"
    "025_track1_hgbm_amplitude_39_closure_attempt_25.yaml"
    "026_track1_hgbm_amplitude_39_closure_attempt_26.yaml"
    "027_track1_hgbm_amplitude_39_closure_attempt_27.yaml"
    "028_track1_hgbm_phase_3_closure_attempt_01.yaml"
    "029_track1_hgbm_phase_3_closure_attempt_02.yaml"
    "030_track1_hgbm_phase_3_closure_attempt_03.yaml"
    "031_track1_hgbm_phase_3_closure_attempt_04.yaml"
    "032_track1_hgbm_phase_3_closure_attempt_05.yaml"
    "033_track1_hgbm_phase_3_closure_attempt_06.yaml"
    "034_track1_hgbm_phase_3_closure_attempt_07.yaml"
    "035_track1_hgbm_phase_3_closure_attempt_08.yaml"
    "036_track1_hgbm_phase_3_closure_attempt_09.yaml"
    "037_track1_hgbm_phase_3_closure_attempt_10.yaml"
    "038_track1_hgbm_phase_3_closure_attempt_11.yaml"
    "039_track1_hgbm_phase_3_closure_attempt_12.yaml"
    "040_track1_hgbm_phase_3_closure_attempt_13.yaml"
    "041_track1_hgbm_phase_3_closure_attempt_14.yaml"
    "042_track1_hgbm_phase_3_closure_attempt_15.yaml"
    "043_track1_hgbm_phase_3_closure_attempt_16.yaml"
    "044_track1_hgbm_phase_3_closure_attempt_17.yaml"
    "045_track1_hgbm_phase_3_closure_attempt_18.yaml"
    "046_track1_hgbm_phase_3_closure_attempt_19.yaml"
    "047_track1_hgbm_phase_3_closure_attempt_20.yaml"
    "048_track1_hgbm_phase_3_closure_attempt_21.yaml"
    "049_track1_hgbm_phase_3_closure_attempt_22.yaml"
    "050_track1_hgbm_phase_3_closure_attempt_23.yaml"
    "051_track1_hgbm_phase_3_closure_attempt_24.yaml"
    "052_track1_hgbm_phase_3_closure_attempt_25.yaml"
    "053_track1_hgbm_phase_3_closure_attempt_26.yaml"
    "054_track1_hgbm_phase_3_closure_attempt_27.yaml"
    "055_track1_hgbm_phase_162_closure_attempt_01.yaml"
    "056_track1_hgbm_phase_162_closure_attempt_02.yaml"
    "057_track1_hgbm_phase_162_closure_attempt_03.yaml"
    "058_track1_hgbm_phase_162_closure_attempt_04.yaml"
    "059_track1_hgbm_phase_162_closure_attempt_05.yaml"
    "060_track1_hgbm_phase_162_closure_attempt_06.yaml"
    "061_track1_hgbm_phase_162_closure_attempt_07.yaml"
    "062_track1_hgbm_phase_162_closure_attempt_08.yaml"
    "063_track1_hgbm_phase_162_closure_attempt_09.yaml"
    "064_track1_hgbm_phase_162_closure_attempt_10.yaml"
    "065_track1_hgbm_phase_162_closure_attempt_11.yaml"
    "066_track1_hgbm_phase_162_closure_attempt_12.yaml"
    "067_track1_hgbm_phase_162_closure_attempt_13.yaml"
    "068_track1_hgbm_phase_162_closure_attempt_14.yaml"
    "069_track1_hgbm_phase_162_closure_attempt_15.yaml"
    "070_track1_hgbm_phase_162_closure_attempt_16.yaml"
    "071_track1_hgbm_phase_162_closure_attempt_17.yaml"
    "072_track1_hgbm_phase_162_closure_attempt_18.yaml"
    "073_track1_hgbm_phase_162_closure_attempt_19.yaml"
    "074_track1_hgbm_phase_162_closure_attempt_20.yaml"
    "075_track1_hgbm_phase_162_closure_attempt_21.yaml"
    "076_track1_hgbm_phase_162_closure_attempt_22.yaml"
    "077_track1_hgbm_phase_162_closure_attempt_23.yaml"
    "078_track1_hgbm_phase_162_closure_attempt_24.yaml"
    "079_track1_hgbm_phase_162_closure_attempt_25.yaml"
    "080_track1_hgbm_phase_162_closure_attempt_26.yaml"
    "081_track1_hgbm_phase_162_closure_attempt_27.yaml"
)
$campaignConfigPathList = @(
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\001_track1_hgbm_amplitude_39_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\002_track1_hgbm_amplitude_39_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\003_track1_hgbm_amplitude_39_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\004_track1_hgbm_amplitude_39_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\005_track1_hgbm_amplitude_39_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\006_track1_hgbm_amplitude_39_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\007_track1_hgbm_amplitude_39_closure_attempt_07.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\008_track1_hgbm_amplitude_39_closure_attempt_08.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\009_track1_hgbm_amplitude_39_closure_attempt_09.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\010_track1_hgbm_amplitude_39_closure_attempt_10.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\011_track1_hgbm_amplitude_39_closure_attempt_11.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\012_track1_hgbm_amplitude_39_closure_attempt_12.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\013_track1_hgbm_amplitude_39_closure_attempt_13.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\014_track1_hgbm_amplitude_39_closure_attempt_14.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\015_track1_hgbm_amplitude_39_closure_attempt_15.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\016_track1_hgbm_amplitude_39_closure_attempt_16.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\017_track1_hgbm_amplitude_39_closure_attempt_17.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\018_track1_hgbm_amplitude_39_closure_attempt_18.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\019_track1_hgbm_amplitude_39_closure_attempt_19.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\020_track1_hgbm_amplitude_39_closure_attempt_20.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\021_track1_hgbm_amplitude_39_closure_attempt_21.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\022_track1_hgbm_amplitude_39_closure_attempt_22.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\023_track1_hgbm_amplitude_39_closure_attempt_23.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\024_track1_hgbm_amplitude_39_closure_attempt_24.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\025_track1_hgbm_amplitude_39_closure_attempt_25.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\026_track1_hgbm_amplitude_39_closure_attempt_26.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\027_track1_hgbm_amplitude_39_closure_attempt_27.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\028_track1_hgbm_phase_3_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\029_track1_hgbm_phase_3_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\030_track1_hgbm_phase_3_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\031_track1_hgbm_phase_3_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\032_track1_hgbm_phase_3_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\033_track1_hgbm_phase_3_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\034_track1_hgbm_phase_3_closure_attempt_07.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\035_track1_hgbm_phase_3_closure_attempt_08.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\036_track1_hgbm_phase_3_closure_attempt_09.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\037_track1_hgbm_phase_3_closure_attempt_10.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\038_track1_hgbm_phase_3_closure_attempt_11.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\039_track1_hgbm_phase_3_closure_attempt_12.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\040_track1_hgbm_phase_3_closure_attempt_13.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\041_track1_hgbm_phase_3_closure_attempt_14.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\042_track1_hgbm_phase_3_closure_attempt_15.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\043_track1_hgbm_phase_3_closure_attempt_16.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\044_track1_hgbm_phase_3_closure_attempt_17.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\045_track1_hgbm_phase_3_closure_attempt_18.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\046_track1_hgbm_phase_3_closure_attempt_19.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\047_track1_hgbm_phase_3_closure_attempt_20.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\048_track1_hgbm_phase_3_closure_attempt_21.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\049_track1_hgbm_phase_3_closure_attempt_22.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\050_track1_hgbm_phase_3_closure_attempt_23.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\051_track1_hgbm_phase_3_closure_attempt_24.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\052_track1_hgbm_phase_3_closure_attempt_25.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\053_track1_hgbm_phase_3_closure_attempt_26.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\054_track1_hgbm_phase_3_closure_attempt_27.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\055_track1_hgbm_phase_162_closure_attempt_01.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\056_track1_hgbm_phase_162_closure_attempt_02.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\057_track1_hgbm_phase_162_closure_attempt_03.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\058_track1_hgbm_phase_162_closure_attempt_04.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\059_track1_hgbm_phase_162_closure_attempt_05.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\060_track1_hgbm_phase_162_closure_attempt_06.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\061_track1_hgbm_phase_162_closure_attempt_07.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\062_track1_hgbm_phase_162_closure_attempt_08.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\063_track1_hgbm_phase_162_closure_attempt_09.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\064_track1_hgbm_phase_162_closure_attempt_10.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\065_track1_hgbm_phase_162_closure_attempt_11.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\066_track1_hgbm_phase_162_closure_attempt_12.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\067_track1_hgbm_phase_162_closure_attempt_13.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\068_track1_hgbm_phase_162_closure_attempt_14.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\069_track1_hgbm_phase_162_closure_attempt_15.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\070_track1_hgbm_phase_162_closure_attempt_16.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\071_track1_hgbm_phase_162_closure_attempt_17.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\072_track1_hgbm_phase_162_closure_attempt_18.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\073_track1_hgbm_phase_162_closure_attempt_19.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\074_track1_hgbm_phase_162_closure_attempt_20.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\075_track1_hgbm_phase_162_closure_attempt_21.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\076_track1_hgbm_phase_162_closure_attempt_22.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\077_track1_hgbm_phase_162_closure_attempt_23.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\078_track1_hgbm_phase_162_closure_attempt_24.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\079_track1_hgbm_phase_162_closure_attempt_25.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\080_track1_hgbm_phase_162_closure_attempt_26.yaml"
    "config\paper_reimplementation\rcim_ml_compensation\exact_model_bank\campaigns\2026-04-20_track1_hgbm_open_cell_full_matrix_closure_campaign\081_track1_hgbm_phase_162_closure_attempt_27.yaml"
)
$runNameList = @(
    "track1_hgbm_amplitude_39_closure_attempt_01"
    "track1_hgbm_amplitude_39_closure_attempt_02"
    "track1_hgbm_amplitude_39_closure_attempt_03"
    "track1_hgbm_amplitude_39_closure_attempt_04"
    "track1_hgbm_amplitude_39_closure_attempt_05"
    "track1_hgbm_amplitude_39_closure_attempt_06"
    "track1_hgbm_amplitude_39_closure_attempt_07"
    "track1_hgbm_amplitude_39_closure_attempt_08"
    "track1_hgbm_amplitude_39_closure_attempt_09"
    "track1_hgbm_amplitude_39_closure_attempt_10"
    "track1_hgbm_amplitude_39_closure_attempt_11"
    "track1_hgbm_amplitude_39_closure_attempt_12"
    "track1_hgbm_amplitude_39_closure_attempt_13"
    "track1_hgbm_amplitude_39_closure_attempt_14"
    "track1_hgbm_amplitude_39_closure_attempt_15"
    "track1_hgbm_amplitude_39_closure_attempt_16"
    "track1_hgbm_amplitude_39_closure_attempt_17"
    "track1_hgbm_amplitude_39_closure_attempt_18"
    "track1_hgbm_amplitude_39_closure_attempt_19"
    "track1_hgbm_amplitude_39_closure_attempt_20"
    "track1_hgbm_amplitude_39_closure_attempt_21"
    "track1_hgbm_amplitude_39_closure_attempt_22"
    "track1_hgbm_amplitude_39_closure_attempt_23"
    "track1_hgbm_amplitude_39_closure_attempt_24"
    "track1_hgbm_amplitude_39_closure_attempt_25"
    "track1_hgbm_amplitude_39_closure_attempt_26"
    "track1_hgbm_amplitude_39_closure_attempt_27"
    "track1_hgbm_phase_3_closure_attempt_01"
    "track1_hgbm_phase_3_closure_attempt_02"
    "track1_hgbm_phase_3_closure_attempt_03"
    "track1_hgbm_phase_3_closure_attempt_04"
    "track1_hgbm_phase_3_closure_attempt_05"
    "track1_hgbm_phase_3_closure_attempt_06"
    "track1_hgbm_phase_3_closure_attempt_07"
    "track1_hgbm_phase_3_closure_attempt_08"
    "track1_hgbm_phase_3_closure_attempt_09"
    "track1_hgbm_phase_3_closure_attempt_10"
    "track1_hgbm_phase_3_closure_attempt_11"
    "track1_hgbm_phase_3_closure_attempt_12"
    "track1_hgbm_phase_3_closure_attempt_13"
    "track1_hgbm_phase_3_closure_attempt_14"
    "track1_hgbm_phase_3_closure_attempt_15"
    "track1_hgbm_phase_3_closure_attempt_16"
    "track1_hgbm_phase_3_closure_attempt_17"
    "track1_hgbm_phase_3_closure_attempt_18"
    "track1_hgbm_phase_3_closure_attempt_19"
    "track1_hgbm_phase_3_closure_attempt_20"
    "track1_hgbm_phase_3_closure_attempt_21"
    "track1_hgbm_phase_3_closure_attempt_22"
    "track1_hgbm_phase_3_closure_attempt_23"
    "track1_hgbm_phase_3_closure_attempt_24"
    "track1_hgbm_phase_3_closure_attempt_25"
    "track1_hgbm_phase_3_closure_attempt_26"
    "track1_hgbm_phase_3_closure_attempt_27"
    "track1_hgbm_phase_162_closure_attempt_01"
    "track1_hgbm_phase_162_closure_attempt_02"
    "track1_hgbm_phase_162_closure_attempt_03"
    "track1_hgbm_phase_162_closure_attempt_04"
    "track1_hgbm_phase_162_closure_attempt_05"
    "track1_hgbm_phase_162_closure_attempt_06"
    "track1_hgbm_phase_162_closure_attempt_07"
    "track1_hgbm_phase_162_closure_attempt_08"
    "track1_hgbm_phase_162_closure_attempt_09"
    "track1_hgbm_phase_162_closure_attempt_10"
    "track1_hgbm_phase_162_closure_attempt_11"
    "track1_hgbm_phase_162_closure_attempt_12"
    "track1_hgbm_phase_162_closure_attempt_13"
    "track1_hgbm_phase_162_closure_attempt_14"
    "track1_hgbm_phase_162_closure_attempt_15"
    "track1_hgbm_phase_162_closure_attempt_16"
    "track1_hgbm_phase_162_closure_attempt_17"
    "track1_hgbm_phase_162_closure_attempt_18"
    "track1_hgbm_phase_162_closure_attempt_19"
    "track1_hgbm_phase_162_closure_attempt_20"
    "track1_hgbm_phase_162_closure_attempt_21"
    "track1_hgbm_phase_162_closure_attempt_22"
    "track1_hgbm_phase_162_closure_attempt_23"
    "track1_hgbm_phase_162_closure_attempt_24"
    "track1_hgbm_phase_162_closure_attempt_25"
    "track1_hgbm_phase_162_closure_attempt_26"
    "track1_hgbm_phase_162_closure_attempt_27"
)

if ($Remote) {
    & ".\scripts\campaigns\track1\exact_paper\run_exact_paper_campaign_remote.ps1" `
        -CampaignName $campaignName `
        -PlanningReportPath $planningReportPath `
        -LauncherRelativePath "scripts\campaigns\track1\exact_paper\run_track1_hgbm_open_cell_full_matrix_closure_campaign.ps1" `
        -CampaignConfigPathList $campaignConfigPathList `
        -RunNameList $runNameList `
        -RemoteHostAlias $RemoteHostAlias `
        -RemoteRepositoryPath $RemoteRepositoryPath `
        -RemoteCondaEnvironmentName $RemoteCondaEnvironmentName
    exit $LASTEXITCODE
}

$nativeExitCode = Invoke-ExactPaperCampaignLocal `
    -CampaignName $campaignName `
    -PlanningReportPath $planningReportPath `
    -CampaignConfigRoot $campaignConfigRoot `
    -CampaignConfigFileNameList $campaignConfigFileNameList `
    -CondaEnvironmentName $CondaEnvironmentName `
    -PythonExecutable $PythonExecutable
exit $nativeExitCode
